apiVersion: v1alpha
kind: Project
metadata:
  name: kafka-connect-test-sdk
  description: ""
spec:
  visibility: private
  repository:
    url: git@github.com:confluentinc/kafka-connect-test-sdk.git
    run_on:
      - branches
      - pull_requests
    pipeline_file: .semaphore/semaphore.yml
    integration_type: github_app
    status:
      pipeline_files:
        - path: .semaphore/semaphore.yml
          level: pipeline
    whitelist:
      branches:
        - master
        - main
        - /^\d+\.\d+\.x$/
        - /^gh-readonly-queue.*/
  custom_permissions: true
  debug_permissions:
    - empty
    - default_branch
    - non_default_branch
    - pull_request
    - forked_pull_request
    - tag
  attach_permissions:
    - default_branch
    - non_default_branch
    - pull_request
    - forked_pull_request
    - tag
